devices:
    myhome/weather/battery:
        ev_name: 'battery'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/temperature:
        ev_name: 'temperature'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/humidity:
        ev_name: 'humidity'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/pressure:
        ev_name: 'pressure'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/wind_speed:
        ev_name: 'wind_speed'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/wind_direction:
        ev_name: 'wind_direction'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/ir_light:
        ev_name: 'ir_light'
        ev_collection: 'Weather'
        factor: 1
        type: '>i'
        update period: 600
    myhome/weather/vis_light:
        ev_name: 'vis_light'
        ev_collection: 'Weather'
        factor: 1
        type: '>i'
        update period: 600
    myhome/weather/uv_index:
        ev_name: 'uv_index'
        ev_collection: 'Weather'
        factor: 100
        type: '>i'
        update period: 600
    myhome/weather/rain_hour:
        ev_name: 'rain_hour'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/rain_day:
        ev_name: 'rain_day'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/wind_speed_2m:
        ev_name: 'wind_speed_2m'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/weather/wind_direction_2m:
        ev_name: 'wind_direction_2m'
        ev_collection: 'Weather'
        factor: 1000
        type: '>i'
        update period: 600
    myhome/pool/water_temp:
        ev_name: 'pool_water_temp'
        ev_collection: 'Home_Temp_Logging'
        factor: 1000
        type: '>i'
        update period: 600
        time offset: 14400
    myhome/pool/humidity:
        ev_name: 'air_humidity'
        ev_collection: 'Home_Temp_Logging'
        factor: 1000
        type: '>i'
        update period: 600
        time offset: 14400

    myhome/pool/air_temp:
        ev_name: air_temp
        ev_collection: 'Home_Temp_Logging'
        factor: 1000
        type: '>i'
        update period: 600
        time offset: 14400
        
    myhome/pool/error_status:
        ev_name: error_status
        ev_collection: 'Home_Temp_Logging'
        type: B
        update period: 600
        time offset: 14400
                  
    myhome/pool/ir_light:
        ev_name: ir_light
        ev_collection: 'Home_Temp_Logging'
        type: '>h'
        update period: 600
        time offset: 14400
        
    myhome/pool/water_temp:
        ev_name: pool_water_temp
        ev_collection: 'Home_Temp_Logging'
        factor: 1000
        type: '>i'
        update period: 600
        time offset: 14400
        
    myhome/pool/pump_speed:
        ev_name: pump_speed
        ev_collection: 'Home_Temp_Logging'
        type: '>h'
        update period: 600
        time offset: 14400
        
    myhome/pool/uv_index:
        ev_name: UV_index
        ev_collection: 'Home_Temp_Logging'
        factor: 100
        type: '>h'
        update period: 600
        time offset: 14400
        
    myhome/pool/visible_light:
        ev_name: visible_light
        ev_collection: 'Home_Temp_Logging'
        type: '>h'
        update period: 600
        time offset: 14400
        
    myhome/pool/flow_switch:
        ev_name: flow
        ev_collection: 'Home_Temp_Logging'
        type: B
        update period: 600
        time offset: 14400
        
    myhome/pool/water_level:
        ev_name: water_level
        ev_collection: 'Home_Temp_Logging'
        factor: 100000
        type: '>i'
        update period: 600
        time offset: 14400
