devices out:
    homeauto/weather/battery:
        topic: battery
        factor: 1000
        device: weather
    homeauto/weather/temperature:
        topic: temperature
        factor: 1000
        device: weather
    homeauto/weather/humidity:
        topic: humidity
        factor: 1000
        device: weather
    homeauto/weather/pressure:
        topic: pressure
        factor: 1000
        device: weather
    homeauto/weather/wind_speed_2m:
        topic: wind_speed_2m
        factor: 1000
        device: weather
    homeauto/weather/wind_direction_2m:
        topic: wind_direction_2m
        factor: 1000
        device: weather
    homeauto/weather/wind_speed:
        topic: wind_speed
        factor: 1000
        device: weather
    homeauto/weather/wind_direction:
        topic: wind_direction
        factor: 1000
        device: weather
    homeauto/weather/ir_light:
        topic: ir_light
        factor: 1
        device: weather
    homeauto/weather/vis_light:
        topic: vis_light
        factor: 1
        device: weather
    homeauto/weather/uv_index:
        topic: uv_index
        factor: 100
        device: weather
    homeauto/weather/rain_hour:
        topic: rain_hour
        factor: 1000
        device: weather
    homeauto/weather/rain_day:
        topic: rain_day
        factor: 1000
        device: weather
    homeauto/pool/water_temp:
        topic: water_temp
        factor: 1000
        device: pool
    homeauto/pool/air_temp:
        topic: air_temp
        factor: 1000
        device: pool
    homeauto/pool/air_humidity:
        topic: air_humidity
        factor: 1000
        device: pool
    homeauto/pool/error:
        topic: error_status
        factor: 1
        device: pool
    homeauto/pool/pump_speed:
        topic: pump_speed
        factor: 1
        device: pool
    homeauto/pool/uv_index:
        topic: uv_index
        factor: 100
        device: pool
    homeauto/pool/ir_light:
        topic: ir_light
        factor: 1000
        device: pool
    homeauto/pool/vis_light:
        topic: visible_light
        factor: 1000
        device: pool
    homeauto/pool/flow_switch:
        topic: flow_switch
        factor: 1
        device: pool
    homeauto/pool/water_level:
        topic: water_level
        factor: 100000
        device: pool

devices in:
    Pool Controller:
        device: pool
        commands:
            setPumpSpeedValue:
                type: numeric
                struct: '>B'
                factor: 1
                topic: homeauto/pool/pump_speed_cmd
