config:
  homeauto/weather/dew_point:
    factor: 555.5555
    offset: 32
    update period: 0
    wu_field: dewptf
  homeauto/weather/humidity:
    factor: 1000
    update period: 0
    wu_field: humidity
  homeauto/weather/pressure:
    factor: 33863.88667
    update period: 0
    wu_field: baromin
  homeauto/weather/rain_day_curr:
    factor: 25400
    update period: 0
    wu_field: dailyrainin
  homeauto/weather/rain_hour_curr:
    factor: 25400
    update period: 0
    wu_field: rainin
  homeauto/weather/temperature:
    factor: 555.5555
    offset: 32
    update period: 0
    wu_field: tempf
  homeauto/weather/wind_direction:
    factor: 1000
    update period: 0
    wu_field: winddir
  homeauto/weather/wind_direction_2m:
    factor: 25400
    update period: 0
    wu_field: winddir_avg2m
  homeauto/weather/wind_direction_gust_10m:
    factor: 1000
    update period: 0
    wu_field: windgustdir
  homeauto/weather/wind_speed:
    factor: 1000
    update period: 0
    wu_field: windspeedmph
  homeauto/weather/wind_speed_2m:
    factor: 1000
    update period: 0
    wu_field: windspdmph_avg2m
  homeauto/weather/wind_speed_gust_10m:
    factor: 1000
    update period: 0
    wu_field: windgustmph
  homeauto/pool/uv_index:
    factor: 100
    update period: 0
    wu_field: UV
url: https://weatherstation.wunderground.com/weatherstation/updateweatherstation.php    
