#!/usr/bin/python

from optparse import OptionParser
from BTLEBroker import mqtt_broker
from BTLEBroker import config

parser = OptionParser()
parser.add_option("-c", "--config", dest="config_file",
                  help="yaml config file for setup", metavar="FILE")
parser.add_option("-n", "--name", dest="name",
                  help="Name of device in yaml file", metavar="FILE")
parser.add_option("-a", "--auth", dest="auth_file",
                  help="yaml config file for auth", metavar="FILE")

if __name__ == "__main__":
    (options, args) = parser.parse_args()
    cfg = config.read_config((options.config_file, options.auth_file))
    mqtt_broker.main(cfg, options.name)
